// Generated by CoffeeScript 1.9.3

/**
 * @package     CleverStyle Music
 * @category    Web Components
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
 */

(function() {
  var music_settings;

  music_settings = cs.music_settings;

  document.webL10n.ready(function() {
    var $body;
    $body = $('body');
    return Polymer('cs-menu', {
      playlist_text: _('playlist'),
      equalizer_text: _('equalizer'),
      sound_environment_text: _('sound-environment'),
      library_text: _('library'),
      rescan_library_text: _('rescan-library'),
      low_performance_mode_text: _('low-performance-mode'),
      low_performance: music_settings.low_performance,
      playlist: function() {
        return document.querySelector('cs-music-playlist').open();
      },
      equalizer: function() {
        document.querySelector('cs-music-equalizer').open();
        return this.back();
      },
      sound_environment: function() {
        document.querySelector('cs-music-sound-environment').open();
        return this.back();
      },
      library: function() {
        return document.querySelector('cs-music-library').open();
      },
      rescan: function() {
        return document.querySelector('cs-music-library-rescan').open();
      },
      performance: function() {
        if (music_settings.low_performance !== confirm(_('low-performance-mode-details'))) {
          music_settings.low_performance = !music_settings.low_performance;
          return location.reload();
        }
      },
      back: function() {
        return $body.removeClass('menu');
      }
    });
  });

}).call(this);
