// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    app
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


/**
 * Randomize array element order in-place.
 * Using Fisher-Yates shuffle algorithm.
*/


(function() {

  if (!window.cs) {
    window.cs = {};
  }

  cs.bus = (function() {
    var subscribers;
    subscribers = {};
    return {
      state: {},
      'on': function(event_name, callback) {
        if (!subscribers[event_name]) {
          subscribers[event_name] = [];
        }
        subscribers[event_name].push(callback);
        return cs.bus;
      },
      'off': function(event_name, callback) {
        if (!subscribers[event_name]) {
          return cs.bus;
        }
        subscribers[event_name].forEach(function(func, index) {
          if (func === callback) {
            delete subscriberssubscribers[event_name][index];
            return false;
          }
        });
        return cs.bus;
      },
      trigger: function(event_name, data) {
        if (subscribers[event_name]) {
          return subscribers[event_name].forEach(function(callback) {
            return setTimeout((function() {
              return callback(data);
            }), 0);
          });
        }
      }
    };
  })();

}).call(this);
