// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    app
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


(function() {

  $(function() {
    var music_library, music_storage;
    music_storage = navigator.getDeviceStorage('music');
    music_library = cs.music_library;
    return music_library.onready(function() {
      return (function() {
        var cursor;
        cursor = music_storage.enumerate();
        cursor.onsuccess = function() {
          var file;
          if (this.result) {
            file = this.result;
            music_library.add(file.name);
            return this["continue"]();
          } else {
            music_library.clean_playlist();
            return music_library.get_next_id_to_play(function(id) {
              return music_library.get(id, function(item) {
                return music_storage.get(item.name).onsuccess = function() {
                  var src;
                  src = window.URL.createObjectURL(this.result);
                  return $('body').append("<p>" + item.name + "</p><audio src='" + src + "' controls></audio>");
                };
              });
            });
          }
        };
        return cursor.onerror = function() {
          return console.error(this.error.name);
        };
      })();
    });
  });

}).call(this);
