// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    app
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


(function() {

  $(function() {
    var add_player_on_page, music_library, music_storage;
    music_storage = navigator.getDeviceStorage('music');
    music_library = cs.music_library;
    add_player_on_page = function() {
      return music_library.get_next_id_to_play(function(id) {
        return music_library.get(id, function(item) {
          return music_storage.get(item.name).onsuccess = function() {
            var src;
            src = window.URL.createObjectURL(this.result);
            return $('body').append("<p>" + item.name + "</p><audio src='" + src + "' controls></audio>");
          };
        });
      });
    };
    return add_player_on_page();
  });

}).call(this);
