// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    Web Components
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


(function() {

  document.webL10n.ready(function() {
    var $body, music_playlist, player;
    $body = $('body');
    music_playlist = cs.music_playlist;
    player = document.querySelector('cs-music-player');
    return Polymer('cs-music-library-action', {
      create_playlist_text: _('create-playlist'),
      add_to_playlist_text: _('add-to-playlist'),
      items: [],
      open: function(items) {
        this.items = items;
        return $body.addClass('library-action');
      },
      create_playlist: function() {
        var _this = this;
        return music_playlist.set(this.items, function() {
          return player.next(function() {
            return $body.removeClass('library-action');
          });
        });
      },
      add_to_playlist: function() {
        var _this = this;
        return music_playlist.append(this.items, function() {
          return $body.removeClass('library-action');
        });
      },
      back: function() {
        return $body.removeClass('library-action');
      }
    });
  });

}).call(this);
