// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    Web Components
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


(function() {

  document.webL10n.ready(function() {
    var $body, music_library, music_library_grouped, music_playlist, player;
    $body = $('body');
    music_library = cs.music_library;
    music_playlist = cs.music_playlist;
    player = document.querySelector('cs-music-player');
    music_library_grouped = document.querySelector('cs-music-library-grouped');
    return Polymer('cs-music-library', {
      all_text: _('all-songs'),
      artists_text: _('artists'),
      albums_text: _('albums'),
      genres_text: _('genres'),
      years_text: _('years'),
      ratings_text: _('ratings'),
      loading: false,
      open: function() {
        this.loading = false;
        return $body.addClass('library');
      },
      group: function(e) {
        var group_field,
          _this = this;
        group_field = $(e.originalTarget).data('group-field');
        return music_library.get_all(function(all) {
          var i, value, _i, _len;
          for (i = _i = 0, _len = all.length; _i < _len; i = ++_i) {
            value = all[i];
            all[i] = value.id;
          }
          switch (group_field) {
            case 'artist':
            case 'album':
            case 'genre':
            case 'year':
            case 'rated':
              return music_library_grouped.open(group_field, all);
            default:
              _this.loading = true;
              return music_playlist.set(all, function() {
                return player.next(function() {
                  $body.removeClass('library menu');
                  return this.loading = false;
                });
              });
          }
        });
      },
      back: function() {
        return $body.removeClass('library');
      }
    });
  });

}).call(this);
