// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    Web Components
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


(function() {

  document.webL10n.ready(function() {
    var $body, music_equalizer, update_level_timeout;
    $body = $('body');
    music_equalizer = cs.music_equalizer;
    update_level_timeout = 0;
    return Polymer('cs-music-equalizer', {
      frequencies: music_equalizer.get_gain_levels(),
      created: function() {
        return this.frequencies = music_equalizer.get_gain_levels();
      },
      ready: function() {
        var frequencies;
        frequencies = this.frequencies;
        return $(this.shadowRoot.querySelectorAll('input[type=range]')).ranger({
          vertical: true,
          label: false,
          min: -20,
          max: 20,
          step: .001,
          callback: function(val) {
            var _this = this;
            clearTimeout(update_level_timeout);
            return update_level_timeout = setTimeout((function() {
              frequencies[$(_this).prev().data('index')] = Math.round(val * 100000) / 100000;
              return music_equalizer.set_gain_levels(frequencies);
            }), 500);
          }
        });
      },
      open: function() {
        return $body.addClass('equalizer');
      },
      back: function() {
        return $body.removeClass('equalizer');
      }
    });
  });

}).call(this);
