// Generated by CoffeeScript 1.9.3

/**
 * @package     CleverStyle Music
 * @category    Web Components
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014-2015, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
 */

(function() {
  document.webL10n.ready(function() {
    var $body, music_playlist, player;
    $body = $('body');
    music_playlist = cs.music_playlist;
    player = document.querySelector('cs-music-player');
    return Polymer('cs-music-library-action', {
      create_playlist_text: _('create-playlist'),
      add_to_playlist_text: _('add-to-playlist'),
      items: [],
      open: function(items) {
        this.items = items;
        return $body.addClass('library-action');
      },
      create_playlist: function() {
        return music_playlist.set(this.items, (function(_this) {
          return function() {
            return player.next(function() {
              return $body.removeClass('library-action');
            });
          };
        })(this));
      },
      add_to_playlist: function() {
        return music_playlist.append(this.items, (function(_this) {
          return function() {
            return $body.removeClass('library-action');
          };
        })(this));
      },
      back: function() {
        return $body.removeClass('library-action');
      }
    });
  });

}).call(this);
