// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    Web Components
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


(function() {

  document.webL10n.ready(function() {
    var $body;
    $body = $(document.querySelector('body'));
    return Polymer('cs-menu', {
      playlist_text: _('playlist'),
      library_text: _('library'),
      rescan_library_text: _('rescan-library'),
      playlist: function() {
        $body.addClass('playlist');
        return setTimeout((function() {
          return document.querySelector('cs-music-playlist').open();
        }), 200);
      },
      library: function() {
        $body.addClass('library');
        return setTimeout((function() {
          return document.querySelector('cs-music-library').open();
        }), 200);
      },
      rescan: function() {
        $body.addClass('library-rescan');
        return setTimeout((function() {
          return document.querySelector('cs-music-library-rescan').open();
        }), 200);
      },
      back: function() {
        return $body.removeClass('menu');
      }
    });
  });

}).call(this);
