// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    Web Components
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


(function() {
  var $body, music_library, music_playlist;

  music_library = cs.music_library;

  music_playlist = cs.music_playlist;

  $body = $(document.querySelector('body'));

  Polymer('cs-menu', {
    rescan_library_text: _('rescan-library'),
    playlist_text: _('playlist'),
    rescan: function() {
      $body.addClass('library-rescan');
      return setTimeout((function() {
        return document.querySelector('cs-music-library-rescan').open();
      }), 200);
    },
    playlist: function() {
      $body.removeClass('menu');
      return setTimeout((function() {
        $body.addClass('playlist');
        return setTimeout((function() {
          return document.querySelector('cs-music-playlist').open();
        }), 200);
      }), 200);
    },
    back: function() {
      return $body.removeClass('menu');
    }
  });

}).call(this);
