// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    Web Components
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


(function() {
  var music_library, music_playlist;

  music_library = cs.music_library;

  music_playlist = cs.music_playlist;

  Polymer('cs-menu', {
    ready: function() {
      var _this = this;
      return setTimeout((function() {
        return _this.style.display = 'block';
      }), 500);
    },
    rescan: function() {
      return music_library.rescan(function() {
        music_playlist.refresh();
        return alert('Rescanned successfully, playlist refreshed');
      });
    },
    back: function() {
      $(this).css({
        marginLeft: '-100vw'
      });
      return $('cs-music-player').css({
        marginLeft: 0
      });
    }
  });

}).call(this);
