// Generated by CoffeeScript 1.4.0

/**
 * @package     CleverStyle Music
 * @category    Web Components
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright   Copyright (c) 2014, Nazar Mokrynskyi
 * @license     MIT License, see license.txt
*/


(function() {

  document.webL10n.ready(function() {
    var $body;
    $body = $('body');
    return Polymer('cs-menu', {
      playlist_text: _('playlist'),
      equalizer_text: _('equalizer'),
      sound_environment_text: _('sound_environment'),
      library_text: _('library'),
      rescan_library_text: _('rescan-library'),
      playlist: function() {
        return document.querySelector('cs-music-playlist').open();
      },
      equalizer: function() {
        document.querySelector('cs-music-equalizer').open();
        return this.back();
      },
      sound_environment: function() {
        document.querySelector('cs-music-sound-environment').open();
        return this.back();
      },
      library: function() {
        return document.querySelector('cs-music-library').open();
      },
      rescan: function() {
        return document.querySelector('cs-music-library-rescan').open();
      },
      back: function() {
        return $body.removeClass('menu');
      }
    });
  });

}).call(this);
